### ISSUE TITLE
Themes does not respect individual apps themes

### ISSUE THREAD

**Issue by Tauin-zz** [DMNerd/Adwaita-OSX#1]
if you use adwaita osx light and you choose dark theme in gnome terminal perferances it wont change to adwaita osx dark

**Comment by DMNerd** [comment]
Thank you for the report. I`ll look into it.

**Comment by Tauin-zz** [comment]
heres some screenshots of the issue
![Screenshot from 2020-07-08 10-09-08](https://user-images.githubusercontent.com/59283710/86858271-dabf4780-c0af-11ea-8ff9-118ee33983ff.png)
![Screenshot from 2020-07-08 10-09-20](https://user-images.githubusercontent.com/59283710/86858286-e3b01900-c0af-11ea-9538-aef5b938c28f.png)

**Comment by DMNerd** [comment]
Closing, after investigation, this is most likely problem with gnome / gnome-tweaks

**Comment by Tauin-zz** [comment]
nope, its fixable. see my fork thing (im not familiar with github), you just need a gtk-dark.css and a gtk-light.css and point them to the corresponding themes, then it works

**Comment by DMNerd** [comment]
> nope, its fixable. see my fork thing (im not familiar with github), you just need a gtk-dark.css and a gtk-light.css and point them to the corresponding themes, then it works

Create Pull request maybe?

**Comment by DMNerd** [comment]
I pulled the changes myself, thank you for the fix. I do not use gnome that much anymore but, I would like this repo to stay as the mainstream
