### ISSUE TITLE
Incorrect width of dropdown menu in nautilus 

### ISSUE THREAD

**Issue by Tauin-zz** [DMNerd/Adwaita-OSX#2]
![Screenshot from 2020-07-08 10-08-06](https://user-images.githubusercontent.com/59283710/86858385-14904e00-c0b0-11ea-9ba4-6cc78e92f4bf.png)
![Screenshot from 2020-07-08 10-08-30](https://user-images.githubusercontent.com/59283710/86858390-165a1180-c0b0-11ea-9272-052ee559c778.png)

**Comment by DMNerd** [comment]
This one is perplexing. What I am doing is actually importing the Adwaita straight from the system... I have a possible fix I am gonna test
